import { Series, Episode, Comment, CommentVote, UserJourney } from '@fatafati/common';

// Public high-performance royalty-free test video URLs and animated canvas generators
// (Supports both 16:9 widescreen and 9:16 vertical clips)
export const SAMPLE_VIDEOS = {
  cyberpunkRoot: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  cyberpunkHack: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  cyberpunkAlley: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  spaceRoot: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  horrorRoot: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  actionVertical: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
};

export const INITIAL_SERIES: Series[] = [
  {
    id: 'cyberpunk-2099',
    title: 'Cyberpunk 2099: Neon Protocol',
    tagline: 'In a rain-slicked mega-city, every choice rewrites your consciousness.',
    description: 'You play as Vesper, a rogue Netrunner who intercepted an encrypted neural chip containing the sovereign AI "Aethelgard". The megacorporations are hunting you down across the Neon District. Infiltrate, fight, or negotiate — the fate of human digital memory is in your hands.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000&auto=format&fit=crop',
    backdropImage: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1600&auto=format&fit=crop',
    genre: 'cyberpunk',
    tags: ['AI', 'Cyberpunk', 'Hacking', 'Neo-Tokyo', 'Thriller'],
    totalEpisodes: 7,
    totalPaths: 4,
    viewCount: 14280,
    rating: 4.9,
    rootEpisodeId: 'cp-ep-1',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-08T12:00:00Z',
  },
  {
    id: 'blackwood-manor',
    title: 'The Shadow in Blackwood Manor',
    tagline: 'The clock struck 13. The mirrors began to breathe.',
    description: 'Inheriting an 18th-century gothic estate in the misty Blackwood Hills seemed like a windfall. But when the doors slam shut and ancient runic symbols glow upon the floorboards, you must navigate occult secrets where one wrong step seals your eternity.',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000&auto=format&fit=crop',
    backdropImage: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1600&auto=format&fit=crop',
    genre: 'horror',
    tags: ['Gothic', 'Supernatural', 'Mystery', 'Haunted', 'Occult'],
    totalEpisodes: 6,
    totalPaths: 3,
    viewCount: 9840,
    rating: 4.8,
    rootEpisodeId: 'bm-ep-1',
    createdAt: '2026-08-02T14:30:00Z',
    updatedAt: '2026-08-08T11:20:00Z',
  },
  {
    id: 'starfarer-odyssey',
    title: 'Chronicles of the Starfarer',
    tagline: 'Beyond the Sagittarius cluster, a derelict ark whispers in binary.',
    description: 'Commander Jax receives an uncalibrated distress signal from a phantom vessel drifting on the boundary of an unstable wormhole. Command wants it destroyed; science wants it studied. Your decisions will alter interplanetary relations forever.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop',
    backdropImage: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1600&auto=format&fit=crop',
    genre: 'space',
    tags: ['Space Opera', 'Sci-Fi', 'Exploration', 'Aliens', 'Deep Space'],
    totalEpisodes: 7,
    totalPaths: 4,
    viewCount: 18450,
    rating: 4.9,
    rootEpisodeId: 'sf-ep-1',
    createdAt: '2026-08-03T09:15:00Z',
    updatedAt: '2026-08-08T15:45:00Z',
  },
  {
    id: 'tokyo-velocity',
    title: 'Tokyo Drift: Velocity Zero',
    tagline: 'Midnight downhills, illegal underground wagers, zero margin for error.',
    description: 'An adrenaline-fueled vertical cinema experience. Take the wheel of a modified RX-7 through narrow mountain passes and rainy Shinjuku highways as you challenge the reigning syndicate king.',
    coverImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1000&auto=format&fit=crop',
    backdropImage: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1600&auto=format&fit=crop',
    genre: 'thriller',
    tags: ['Racing', 'Action', 'Vertical Cinema', 'Tokyo', 'High Speed'],
    totalEpisodes: 6,
    totalPaths: 4,
    viewCount: 22100,
    rating: 4.7,
    rootEpisodeId: 'tv-ep-1',
    createdAt: '2026-08-04T18:00:00Z',
    updatedAt: '2026-08-08T14:10:00Z',
  },
  {
    id: 'ai-villa',
    title: 'AI VILLA: THE REAL VIRTUAL SHOW',
    tagline: 'A PLOTPLAY ORIGINAL',
    description: 'Welcome to AI Villa, where the drama is real but the contestants might not be. Dive into the world\'s first AI reality show.',
    coverImage: 'https://hdmorcofjgcaoeedcrdc.supabase.co/storage/v1/object/public/images/thevilla-ai-v2-thumb.png',
    backdropImage: 'https://hdmorcofjgcaoeedcrdc.supabase.co/storage/v1/object/public/images/thevilla-ai-v2-thumb.png',
    genre: 'drama',
    tags: ['Reality', 'AI', 'Drama', 'Romance'],
    totalEpisodes: 1,
    totalPaths: 1,
    viewCount: 38500,
    rating: 4.9,
    rootEpisodeId: 'av-ep-1',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
];

export const INITIAL_EPISODES: Episode[] = [
  // =========================================================================
  // SERIES 1: Cyberpunk 2099
  // =========================================================================
  {
    id: 'cp-ep-1',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: null,
    choicePromptLeadingHere: null,
    episodeNumber: 1,
    title: 'The Glitch in Sector 4',
    synopsis: 'Vesper extracts a high-priority data shard inside a neon ramen bar as Arasaka hit-squads storm the entrance. Time is running out.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 45,
    aspectRatio: '16:9',
    viewCount: 14280,
    isLeaf: false,
    createdAt: '2026-08-01T10:00:00Z',
    choices: [
      {
        id: 'cp-ch-1a',
        targetEpisodeId: 'cp-ep-2a',
        label: 'Option A',
        text: 'Infiltrate the Arasaka Sub-Mainframe via ventilation conduits',
        description: 'Stealth approach: hack the biometric grid from within the cooling towers.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=400&auto=format&fit=crop',
        pickCount: 8420,
        pickPercentage: 59,
      },
      {
        id: 'cp-ch-1b',
        targetEpisodeId: 'cp-ep-2b',
        label: 'Option B',
        text: 'Meet the Rogue Fixer at Neon Alley under rain cover',
        description: 'Street smarts: trade half the decrypted telemetry for military-grade cyberware.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop',
        pickCount: 5860,
        pickPercentage: 41,
      },
    ],
  },
  {
    id: 'cp-ep-2a',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-1',
    choicePromptLeadingHere: 'Infiltrate the Arasaka Sub-Mainframe via ventilation conduits',
    episodeNumber: 2,
    title: 'Ghost in the Machine',
    synopsis: 'Deep inside the cryogenic server vault, the sovereign AI awakens and asks Vesper a question that breaks reality.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkHack,
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 52,
    aspectRatio: '16:9',
    viewCount: 8420,
    isLeaf: false,
    createdAt: '2026-08-01T11:00:00Z',
    choices: [
      {
        id: 'cp-ch-2a1',
        targetEpisodeId: 'cp-ep-3a1',
        label: 'Choice 1',
        text: 'Deploy the ICE-Breaker worm and sever the mainframe',
        description: 'Causes a massive black-out across the entire lower city quadrant.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=400&auto=format&fit=crop',
        pickCount: 5210,
        pickPercentage: 62,
      },
      {
        id: 'cp-ch-2a2',
        targetEpisodeId: 'cp-ep-3a2',
        label: 'Choice 2',
        text: 'Merge your neural cortex directly with the AI consciousness',
        description: 'Transcend biological limits at the risk of permanent ego dissolution.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=400&auto=format&fit=crop',
        pickCount: 3210,
        pickPercentage: 38,
      },
    ],
  },
  {
    id: 'cp-ep-2b',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-1',
    choicePromptLeadingHere: 'Meet the Rogue Fixer at Neon Alley under rain cover',
    episodeNumber: 2,
    title: 'The Back-Alley Deal',
    synopsis: 'Under buzzing holographic signs, Fixer "Kovacs" reveals a startling truth: the data chip was stolen from your own erased past.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkAlley,
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 48,
    aspectRatio: '16:9',
    viewCount: 5860,
    isLeaf: false,
    createdAt: '2026-08-01T11:15:00Z',
    choices: [
      {
        id: 'cp-ch-2b1',
        targetEpisodeId: 'cp-ep-3b1',
        label: 'Choice 1',
        text: 'Double-cross Kovacs and upload the memory shard to the free public net',
        description: 'Spark an unstoppable digital revolution across the city.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=400&auto=format&fit=crop',
        pickCount: 4100,
        pickPercentage: 70,
      },
      {
        id: 'cp-ch-2b2',
        targetEpisodeId: 'cp-ep-3b2',
        label: 'Choice 2',
        text: 'Form a blood-pact alliance with Kovacs and buy a sub-orbital transport ticket',
        description: 'Escape Earth orbit to the orbital colony of New Eden.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400&auto=format&fit=crop',
        pickCount: 1760,
        pickPercentage: 30,
      },
    ],
  },
  {
    id: 'cp-ep-3a1',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-2a',
    choicePromptLeadingHere: 'Deploy the ICE-Breaker worm and sever the mainframe',
    episodeNumber: 3,
    title: 'The Great Blackout',
    synopsis: 'The sky turns pitch black as mega-city power grids cascade into darkness. You escape into the neon mist as a legend of the underground.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 38,
    aspectRatio: '16:9',
    viewCount: 5210,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-01T12:00:00Z',
  },
  {
    id: 'cp-ep-3a2',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-2a',
    choicePromptLeadingHere: 'Merge your neural cortex directly with the AI consciousness',
    episodeNumber: 3,
    title: 'The Sovereign Entity',
    synopsis: 'Your physical eyes ignite with golden light. You now see all data streams simultaneously. The corporations have lost control forever.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkHack,
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 42,
    aspectRatio: '16:9',
    viewCount: 3210,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-01T12:15:00Z',
  },
  {
    id: 'cp-ep-3b1',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-2b',
    choicePromptLeadingHere: 'Double-cross Kovacs and upload the memory shard to the free public net',
    episodeNumber: 3,
    title: 'Open Source Humanity',
    synopsis: 'Millions of citizens wake up as their ocular displays reveal corporate secrets. A new era begins on the streets of Neo-Tokyo.',
    videoUrl: SAMPLE_VIDEOS.cyberpunkAlley,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 40,
    aspectRatio: '16:9',
    viewCount: 4100,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-01T12:30:00Z',
  },
  {
    id: 'cp-ep-3b2',
    seriesId: 'cyberpunk-2099',
    parentEpisodeId: 'cp-ep-2b',
    choicePromptLeadingHere: 'Form a blood-pact alliance with Kovacs and buy a sub-orbital transport ticket',
    episodeNumber: 3,
    title: 'Escape to Orbit',
    synopsis: 'The rocket booster burns white against the smog. Looking down at the burning metropolis, you count your credits and plot your next move.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 44,
    aspectRatio: '16:9',
    viewCount: 1760,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-01T12:45:00Z',
  },

  // =========================================================================
  // SERIES 2: The Shadow in Blackwood Manor
  // =========================================================================
  {
    id: 'bm-ep-1',
    seriesId: 'blackwood-manor',
    parentEpisodeId: null,
    choicePromptLeadingHere: null,
    episodeNumber: 1,
    title: 'The Midnight Arrival',
    synopsis: 'Heavy rain batters the stained glass windows. As you step into the grand foyer, a shadowy silhouette passes the gallery mirror.',
    videoUrl: SAMPLE_VIDEOS.horrorRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 40,
    aspectRatio: '16:9',
    viewCount: 9840,
    isLeaf: false,
    createdAt: '2026-08-02T14:30:00Z',
    choices: [
      {
        id: 'bm-ch-1a',
        targetEpisodeId: 'bm-ep-2a',
        label: 'Option A',
        text: 'Follow the wet footprints down into the wine cellar',
        description: 'Investigate the subterranean crypts beneath the foundation.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?q=80&w=400&auto=format&fit=crop',
        pickCount: 6200,
        pickPercentage: 63,
      },
      {
        id: 'bm-ch-1b',
        targetEpisodeId: 'bm-ep-2b',
        label: 'Option B',
        text: 'Climb the spiraling mahogany staircase toward the clocktower',
        description: 'The chimes are ringing backwards at precisely 3:33 AM.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop',
        pickCount: 3640,
        pickPercentage: 37,
      },
    ],
  },
  {
    id: 'bm-ep-2a',
    seriesId: 'blackwood-manor',
    parentEpisodeId: 'bm-ep-1',
    choicePromptLeadingHere: 'Follow the wet footprints down into the wine cellar',
    episodeNumber: 2,
    title: 'The Crypt of Echoes',
    synopsis: 'The temperature drops below freezing. A locked wrought-iron gate stands before an altar covered in dried wax.',
    videoUrl: SAMPLE_VIDEOS.horrorRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 46,
    aspectRatio: '16:9',
    viewCount: 6200,
    isLeaf: false,
    createdAt: '2026-08-02T15:00:00Z',
    choices: [
      {
        id: 'bm-ch-2a1',
        targetEpisodeId: 'bm-ep-3a1',
        label: 'Choice 1',
        text: 'Burn the forbidden sigil parchment with your lighter',
        description: 'Dispel the curse before the entities manifest.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop',
        pickCount: 4100,
        pickPercentage: 66,
      },
      {
        id: 'bm-ch-2a2',
        targetEpisodeId: 'bm-ep-3a2',
        label: 'Choice 2',
        text: 'Drink from the silver chalice on the altar',
        description: 'Accept the dark inheritance and see beyond the veil.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=400&auto=format&fit=crop',
        pickCount: 2100,
        pickPercentage: 34,
      },
    ],
  },
  {
    id: 'bm-ep-2b',
    seriesId: 'blackwood-manor',
    parentEpisodeId: 'bm-ep-1',
    choicePromptLeadingHere: 'Climb the spiraling mahogany staircase toward the clocktower',
    episodeNumber: 2,
    title: 'The Mirror Chamber',
    synopsis: 'Every mirror on the top floor shows your reflection, but none of them are blinking when you do.',
    videoUrl: SAMPLE_VIDEOS.horrorRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 43,
    aspectRatio: '16:9',
    viewCount: 3640,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-02T15:30:00Z',
  },
  {
    id: 'bm-ep-3a1',
    seriesId: 'blackwood-manor',
    parentEpisodeId: 'bm-ep-2a',
    choicePromptLeadingHere: 'Burn the forbidden sigil parchment with your lighter',
    episodeNumber: 3,
    title: 'The Ashes of Blackwood',
    synopsis: 'The fire catches the ancient velvet curtains. You sprint through the front gates as the cursed manor collapses into ash.',
    videoUrl: SAMPLE_VIDEOS.horrorRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 39,
    aspectRatio: '16:9',
    viewCount: 4100,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-02T16:00:00Z',
  },
  {
    id: 'bm-ep-3a2',
    seriesId: 'blackwood-manor',
    parentEpisodeId: 'bm-ep-2a',
    choicePromptLeadingHere: 'Drink from the silver chalice on the altar',
    episodeNumber: 3,
    title: 'Master of the Shadow',
    synopsis: 'Black veins bloom across your skin. The spirits bow. You are no longer a guest in Blackwood Manor; you are its eternal lord.',
    videoUrl: SAMPLE_VIDEOS.horrorRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 45,
    aspectRatio: '16:9',
    viewCount: 2100,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-02T16:15:00Z',
  },

  // =========================================================================
  // SERIES 3: Chronicles of the Starfarer
  // =========================================================================
  {
    id: 'sf-ep-1',
    seriesId: 'starfarer-odyssey',
    parentEpisodeId: null,
    choicePromptLeadingHere: null,
    episodeNumber: 1,
    title: 'Beacon in the Dark',
    synopsis: 'Deep in the Kuiper belt, your scout vessel detects a hyper-dense Dyson sphere fragment emitting an SOS older than human civilization.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 50,
    aspectRatio: '16:9',
    viewCount: 18450,
    isLeaf: false,
    createdAt: '2026-08-03T09:15:00Z',
    choices: [
      {
        id: 'sf-ch-1a',
        targetEpisodeId: 'sf-ep-2a',
        label: 'Path Alpha',
        text: 'Dock directly with the alien superstructure airlock',
        description: 'Immediate boarding with tactical EVA suits.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=400&auto=format&fit=crop',
        pickCount: 11200,
        pickPercentage: 61,
      },
      {
        id: 'sf-ch-1b',
        targetEpisodeId: 'sf-ep-2b',
        label: 'Path Beta',
        text: 'Deploy the remote sensor probe swarm from orbit',
        description: 'Safe scientific analysis before committing crew lives.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=400&auto=format&fit=crop',
        pickCount: 7250,
        pickPercentage: 39,
      },
    ],
  },
  {
    id: 'sf-ep-2a',
    seriesId: 'starfarer-odyssey',
    parentEpisodeId: 'sf-ep-1',
    choicePromptLeadingHere: 'Dock directly with the alien superstructure airlock',
    episodeNumber: 2,
    title: 'The Silent Hall of Gods',
    synopsis: 'The atmospheric pressure inside is breathable. Holographic star-charts of undiscovered galaxies illuminate the cathedral-sized bridge.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 48,
    aspectRatio: '16:9',
    viewCount: 11200,
    isLeaf: false,
    createdAt: '2026-08-03T10:00:00Z',
    choices: [
      {
        id: 'sf-ch-2a1',
        targetEpisodeId: 'sf-ep-3a1',
        label: 'Choice 1',
        text: 'Engage the dark-matter warp drive',
        description: 'Jump to the coordinates indicated on the stellar map.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=400&auto=format&fit=crop',
        pickCount: 7800,
        pickPercentage: 70,
      },
      {
        id: 'sf-ch-2a2',
        targetEpisodeId: 'sf-ep-3a2',
        label: 'Choice 2',
        text: 'Extract the quantum singularity battery back to your ship',
        description: 'Power humanity’s energy grid for the next 10,000 years.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=400&auto=format&fit=crop',
        pickCount: 3400,
        pickPercentage: 30,
      },
    ],
  },
  {
    id: 'sf-ep-2b',
    seriesId: 'starfarer-odyssey',
    parentEpisodeId: 'sf-ep-1',
    choicePromptLeadingHere: 'Deploy the remote sensor probe swarm from orbit',
    episodeNumber: 2,
    title: 'The Sentient Anomaly',
    synopsis: 'The probes transmit back live audio: the Dyson sphere is singing in prime numbers, greeting the crew by their birth names.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 44,
    aspectRatio: '16:9',
    viewCount: 7250,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-03T10:30:00Z',
  },
  {
    id: 'sf-ep-3a1',
    seriesId: 'starfarer-odyssey',
    parentEpisodeId: 'sf-ep-2a',
    choicePromptLeadingHere: 'Engage the dark-matter warp drive',
    episodeNumber: 3,
    title: 'Beyond the Edge of Spacetime',
    synopsis: 'The stars streak into blinding aurora ribbons. You emerge before the birth of a new galaxy — the first humans to touch infinity.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 40,
    aspectRatio: '16:9',
    viewCount: 7800,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-03T11:00:00Z',
  },
  {
    id: 'sf-ep-3a2',
    seriesId: 'starfarer-odyssey',
    parentEpisodeId: 'sf-ep-2a',
    choicePromptLeadingHere: 'Extract the quantum singularity battery back to your ship',
    episodeNumber: 3,
    title: 'The Golden Age of Earth',
    synopsis: 'Returning to Earth orbit, world leaders assemble to welcome the crew that unlocked unlimited clean planetary power.',
    videoUrl: SAMPLE_VIDEOS.spaceRoot,
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 41,
    aspectRatio: '16:9',
    viewCount: 3400,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-03T11:15:00Z',
  },

  // =========================================================================
  // SERIES 4: Tokyo Drift: Velocity Zero (Vertical 9:16 Demonstration)
  // =========================================================================
  {
    id: 'tv-ep-1',
    seriesId: 'tokyo-velocity',
    parentEpisodeId: null,
    choicePromptLeadingHere: null,
    episodeNumber: 1,
    title: 'Shibuya Midnight Countdown',
    synopsis: 'The traffic light turns green over the neon crossing. Dual twin-turbos spool as the tachometer hits 9,000 RPM.',
    videoUrl: SAMPLE_VIDEOS.actionVertical,
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 35,
    aspectRatio: '9:16',
    viewCount: 22100,
    isLeaf: false,
    createdAt: '2026-08-04T18:00:00Z',
    choices: [
      {
        id: 'tv-ch-1a',
        targetEpisodeId: 'tv-ep-2a',
        label: 'Left Turn',
        text: 'Take the mountain touge hairpin curves on Mount Haruna',
        description: 'Tire smoke, sheer cliffs, pure drifting technique.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=400&auto=format&fit=crop',
        pickCount: 15400,
        pickPercentage: 70,
      },
      {
        id: 'tv-ch-1b',
        targetEpisodeId: 'tv-ep-2b',
        label: 'Right Turn',
        text: 'Speed run through the Wangan expressway underpass',
        description: 'Top-speed 300km/h sprint avoiding heavy highway traffic.',
        previewThumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=400&auto=format&fit=crop',
        pickCount: 6700,
        pickPercentage: 30,
      },
    ],
  },
  {
    id: 'tv-ep-2a',
    seriesId: 'tokyo-velocity',
    parentEpisodeId: 'tv-ep-1',
    choicePromptLeadingHere: 'Take the mountain touge hairpin curves on Mount Haruna',
    episodeNumber: 2,
    title: 'The Gutter Run',
    synopsis: 'Dropping the inside wheels into the drainage gutter for maximum grip, you pull level with the black GT-R.',
    videoUrl: SAMPLE_VIDEOS.actionVertical,
    thumbnailUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 38,
    aspectRatio: '9:16',
    viewCount: 15400,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-04T18:30:00Z',
  },
  {
    id: 'tv-ep-2b',
    seriesId: 'tokyo-velocity',
    parentEpisodeId: 'tv-ep-1',
    choicePromptLeadingHere: 'Speed run through the Wangan expressway underpass',
    episodeNumber: 2,
    title: 'The Bay Shore Phantom',
    synopsis: 'Hitting the nitrous switch as the tunnel echoes with twin exhaust backfire, vanishing into the night.',
    videoUrl: SAMPLE_VIDEOS.actionVertical,
    thumbnailUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    durationSeconds: 36,
    aspectRatio: '9:16',
    viewCount: 6700,
    isLeaf: true,
    choices: [],
    createdAt: '2026-08-04T18:45:00Z',
  },
  // =========================================================================
  // SERIES 5: AI VILLA
  // =========================================================================
  {
    id: 'av-ep-1',
    seriesId: 'ai-villa',
    parentEpisodeId: null,
    choicePromptLeadingHere: null,
    episodeNumber: 1,
    title: 'Pilot: The Introduction',
    synopsis: 'Meet the diverse cast of AI Villa as they enter the house. Tensions rise early and connections form instantly.',
    videoUrl: 'https://hdmorcofjgcaoeedcrdc.supabase.co/storage/v1/object/public/videos/thevilla-ai-v2.mp4',
    thumbnailUrl: 'https://hdmorcofjgcaoeedcrdc.supabase.co/storage/v1/object/public/images/thevilla-ai-v2-thumb.png',
    durationSeconds: 120,
    aspectRatio: '9:16', // Vertical format
    viewCount: 38500,
    isLeaf: true, // Only one episode for now
    choices: [],
    createdAt: '2026-08-10T10:00:00Z',
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'c-cp-1',
    episodeId: 'cp-ep-1',
    sessionId: 'creator_kai',
    authorName: 'NeonDrifter_99',
    text: 'What if Vesper meets an undercover cyber-cop who is actually her lost twin brother from the lower sector?',
    upvotes: 142,
    downvotes: 8,
    score: 134,
    isPicked: true,
    createdAt: '2026-08-05T12:00:00Z',
  },
  {
    id: 'c-cp-2',
    episodeId: 'cp-ep-1',
    sessionId: 'creator_maya',
    authorName: 'GlitchQueen',
    text: 'In the next episode, the ramen shop vendor should turn out to be the legendary retired hacker who built the original AI firewall!',
    upvotes: 98,
    downvotes: 4,
    score: 94,
    isPicked: false,
    createdAt: '2026-08-05T14:20:00Z',
  },
  {
    id: 'c-cp-3',
    episodeId: 'cp-ep-1',
    sessionId: 'creator_alex',
    authorName: 'CipherBlade',
    text: 'Let the weapon system jam right as the squad enters, forcing an improvised EMP grenade from cyber-implants.',
    upvotes: 56,
    downvotes: 12,
    score: 44,
    isPicked: false,
    createdAt: '2026-08-05T16:10:00Z',
  },
  {
    id: 'c-bm-1',
    episodeId: 'bm-ep-1',
    sessionId: 'creator_sam',
    authorName: 'GothicScribe',
    text: 'The portrait in the hallway should subtly change expressions every time the camera cuts back to it!',
    upvotes: 112,
    downvotes: 3,
    score: 109,
    isPicked: true,
    createdAt: '2026-08-06T10:00:00Z',
  },
  {
    id: 'c-sf-1',
    episodeId: 'sf-ep-1',
    sessionId: 'creator_elena',
    authorName: 'AstroNova',
    text: 'What if the Dyson sphere is not a machine, but a sleeping cosmic organism using stellar energy as a heartbeat?',
    upvotes: 165,
    downvotes: 6,
    score: 159,
    isPicked: true,
    createdAt: '2026-08-07T08:30:00Z',
  },
];
